name: android build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: the ndk thingy
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r10e
     
    - name: run the things and all idk
      run: |
         ./waf configure -T debug
         ./waf build
